// <auto-generated />
namespace Provodnik.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class init28 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(init28));
        
        string IMigrationMetadata.Id
        {
            get { return "202303211746296_init28"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
